FROM mcr.microsoft.com/dotnet/runtime:9.0 AS base
WORKDIR /app

USER app
FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:9.0 AS build
ARG configuration=Release
WORKDIR /src
COPY ["Multitalks2/Multitalks2.csproj", "Multitalks2/"]
RUN dotnet restore "Multitalks2/Multitalks2.csproj"
COPY . .
WORKDIR "/src/Multitalks2"
RUN dotnet build "Multitalks2.csproj" -c $configuration -o /app/build

FROM build AS publish
ARG configuration=Release
RUN dotnet publish "Multitalks2.csproj" -c $configuration -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Multitalks2.dll"]
